theme: osuny
_merge: deep
params:
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  logo:
    header: "/assets/images/aorg-black.svg"
    footer: "/assets/images/aorg-white.svg"
  debug:
     productionUrl: "https://www.aorganisation.org"