[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/organisations/noesya/"
to = "/annuaire/noesya/"

[[redirects]]
from = "/fr/equipe/"
to = "/equipe/"

[[redirects]]
from = "/fr/charte/"
to = "/charte/"

[[redirects]]
from = "/fr/equipe/equipe-editoriale/"
to = "/equipe/equipe-editoriale/"

[[redirects]]
from = "/fr/organisations/"
to = "/annuaire/"

[[redirects]]
from = "/en/equipe/"
to = "/equipe/"

[[redirects]]
from = "/en/"
to = "/"

[[redirects]]
from = "/fr/equipe/edouard-jourdain/"
to = "/equipe/edouard-jourdain/"

[[redirects]]
from = "/fr/ressources/2023-06-22-lage-du-faire-hacking-travail-anarchie/"
to = "/ressources/2023-06-22-lage-du-faire-hacking-travail-anarchie/"

[[redirects]]
from = "/fr/annuaire/noesya/"
to = "/annuaire/noesya/"

[[redirects]]
from = "/fr/actualites/"
to = "/ressources/"

[[redirects]]
from = "/fr/politique-de-confidentialite/"
to = "/politique-de-confidentialite/"

[[redirects]]
from = "/fr/mentions-legales/"
to = "/mentions-legales/"

[[redirects]]
from = "/fr/accessibilite/"
to = "/accessibilite/"

[[redirects]]
from = "/organisations/"
to = "/annuaire/"

[[redirects]]
from = "/fr/plan-du-site/"
to = "/plan-du-site/"

[[redirects]]
from = "/fr/ressources/"
to = "/ressources/"

[[redirects]]
from = "/fr/actualites/2023-06-22-lage-du-faire-hacking-travail-anarchie/"
to = "/ressources/2023-06-22-lage-du-faire-hacking-travail-anarchie/"

[[redirects]]
from = "/fr/annuaire/"
to = "/annuaire/"

[[redirects]]
from = "/en/organisations-1/"
to = "/organisations-1/"

[[redirects]]
from = "/fr/certification/"
to = "/certification/"

[[redirects]]
from = "/actualites/"
to = "/ressources/"

[[redirects]]
from = "/fr/organisations/noesya/"
to = "/annuaire/noesya/"

[[redirects]]
from = "/fr/equipe/arnaud-levy/"
to = "/equipe/arnaud-levy/"

[[redirects]]
from = "/fr/equipe/edouard-jourdain-1/"
to = "/equipe/edouard-jourdain/"

[[redirects]]
from = "/fr/"
to = "/"

